// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

/*
Package go_micro_srv_consignment is a generated protocol buffer package.

It is generated from these files:
	proto/consignment/consignment.proto

It has these top-level messages:
	Consignment
	Container
	GetRequest
	Response
*/
package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id               *string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description      *string      `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Weight           *int32       `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers       []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	VesselId         *string      `protobuf:"bytes,5,opt,name=vessel_id" json:"vessel_id,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Consignment) Reset()                    { *m = Consignment{} }
func (m *Consignment) String() string            { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()               {}
func (*Consignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Consignment) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil && m.VesselId != nil {
		return *m.VesselId
	}
	return ""
}

type Container struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId       *string `protobuf:"bytes,2,opt,name=customer_id" json:"customer_id,omitempty"`
	Origin           *string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	UserId           *string `protobuf:"bytes,4,opt,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil && m.CustomerId != nil {
		return *m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

// Created a blank get request
type GetRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
	Created     *bool        `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Consignment *Consignment `protobuf:"bytes,2,opt,name=consignment" json:"consignment,omitempty"`
	// Added a pluralised consignment to our generic response message
	Consignments     []*Consignment `protobuf:"bytes,3,rep,name=consignments" json:"consignments,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetCreated() bool {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	// Created a new method
	GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.consignment.ShippingService/CreateConsignment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.consignment.ShippingService/GetConsignments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
	// Created a new method
	GetConsignments(context.Context, *GetRequest) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.ShippingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GetConsignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetConsignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.ShippingService/GetConsignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetConsignments(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.consignment.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShippingService_CreateConsignment_Handler,
		},
		{
			MethodName: "GetConsignments",
			Handler:    _ShippingService_GetConsignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}

func init() { proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x4d, 0x4f, 0x32, 0x31,
	0x10, 0x7e, 0xcb, 0xc7, 0x2b, 0x3b, 0x4b, 0x24, 0xd4, 0x4b, 0xe3, 0x89, 0x2c, 0x9a, 0x70, 0xaa,
	0x09, 0x17, 0x13, 0x3d, 0x72, 0xe0, 0xe4, 0x05, 0xce, 0x46, 0x49, 0x99, 0x2c, 0x93, 0x48, 0xbb,
	0x76, 0x0a, 0xfe, 0x07, 0xcf, 0xfe, 0x32, 0x7f, 0x91, 0xa1, 0x04, 0x68, 0x4c, 0x30, 0x7b, 0xdb,
	0xed, 0xf3, 0x39, 0x0f, 0x0c, 0x2b, 0xef, 0x82, 0xbb, 0x33, 0xce, 0x32, 0x95, 0x76, 0x8d, 0x36,
	0xa4, 0xdf, 0x3a, 0xa2, 0x52, 0x95, 0x4e, 0xaf, 0xc9, 0x78, 0xa7, 0xd9, 0x6f, 0x75, 0x82, 0x17,
	0x9f, 0x02, 0xf2, 0xc9, 0xe9, 0x5f, 0x02, 0x34, 0x68, 0xa9, 0xc4, 0x40, 0x8c, 0x32, 0x79, 0x05,
	0xf9, 0x12, 0xd9, 0x78, 0xaa, 0x02, 0x39, 0xab, 0x1a, 0xf1, 0xf1, 0x12, 0xfe, 0x7f, 0x20, 0x95,
	0xab, 0xa0, 0x9a, 0x03, 0x31, 0x6a, 0xcb, 0x7b, 0x00, 0xe3, 0x6c, 0x58, 0x90, 0x45, 0xcf, 0xaa,
	0x35, 0x68, 0x8e, 0xf2, 0xf1, 0x50, 0x9f, 0xcb, 0xd3, 0x93, 0x03, 0x57, 0xf6, 0x21, 0xdb, 0x22,
	0x33, 0xbe, 0xbd, 0xd0, 0x52, 0xb5, 0x77, 0xde, 0xc5, 0x13, 0x64, 0x27, 0xfc, 0x57, 0x13, 0xb3,
	0xe1, 0xe0, 0xd6, 0xe8, 0x77, 0xec, 0x63, 0x13, 0xe7, 0xa9, 0x24, 0x1b, 0x9b, 0x64, 0xb2, 0x07,
	0x17, 0x1b, 0xde, 0x13, 0x5a, 0xd1, 0xae, 0x0b, 0x30, 0xc5, 0x30, 0xc3, 0xf7, 0x0d, 0x72, 0x28,
	0xbe, 0x04, 0x74, 0x66, 0xc8, 0x95, 0xb3, 0x8c, 0x3b, 0xae, 0xf1, 0xb8, 0x08, 0xb8, 0x4f, 0xe8,
	0xc8, 0x07, 0xc8, 0x93, 0x9a, 0x31, 0x21, 0x1f, 0xdf, 0xfe, 0x79, 0xc7, 0x71, 0xb3, 0x47, 0xe8,
	0x26, 0x10, 0xab, 0x66, 0x1c, 0xa1, 0x9e, 0x78, 0xfc, 0x2d, 0xa0, 0x37, 0x5f, 0x51, 0x55, 0x91,
	0x2d, 0xe7, 0xe8, 0xb7, 0x64, 0x50, 0xbe, 0x42, 0x7f, 0x12, 0xdb, 0xa5, 0x29, 0xf5, 0xfc, 0xae,
	0x8b, 0xf3, 0xb4, 0xc3, 0xf5, 0xc5, 0x3f, 0xf9, 0x0c, 0xbd, 0x29, 0x86, 0x44, 0xc7, 0xf2, 0xe6,
	0xbc, 0xf0, 0xb4, 0x62, 0x3d, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xfb, 0x32, 0x76,
	0x95, 0x02, 0x00, 0x00,
}
